services:
  scanly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scanly
    environment:
      - FORCE_INTERACTIVE=true
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ${MEDIA_SOURCE_DIR:-/path/to/your/media}:/media/source:ro
      - ${MEDIA_LIBRARY_DIR:-/path/to/your/library}:/media/library
    stdin_open: true
    tty: true
    restart: unless-stopped
    init: true